### PR TITLE
Add status_code support

### PR DESCRIPTION
**Pull request by wreis**
When defined, only set/unset/append headers for that specific response code.

### CODE REVIEW

**Comment by nihen** [comment]
This module's target is only header.
I like "keep it simple".

**Comment by wreis** [comment]
What does make you think that patch is trying to change anything else than header?

**Comment by nihen** [comment]
it is status code.

**Comment by wreis** [comment]
What?! No! It's only using it to mangle headers -based- on status code. Lets say that someone needs to set some headers only for 404 responses. It doesnt change the status code.

**Comment by nihen** [comment]
oh, sorry.
I misunderstanding this patch.

but I don't like this approach.

I think to make something like a "Plack::Builder::Conditionals::Response" is good.

**Pull request closed without merging**
